class Ingredient {
  final String name;
  final List<String> units;

  Ingredient({required this.name, required this.units});
}

final List<Ingredient> ingredients = [
  Ingredient(name: 'Acar', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Air', units: ['ml', 'gelas']),
  Ingredient(name: 'Bawang Bombay', units: ['gram', 'siung']),
  Ingredient(name: 'Bawang Daun', units: ['gram', 'ikat']),
  Ingredient(name: 'Bawang Goreng', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Bawang Merah', units: ['gram', 'siung']),
  Ingredient(name: 'Bawang Putih', units: ['gram', 'siung']),
  Ingredient(name: 'Bayam', units: ['gram', 'ikat']),
  Ingredient(name: 'Bebek', units: ['gram', 'potong']),
  Ingredient(name: 'Beras', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Bihun', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Brokoli', units: ['gram', 'ikat']),
  Ingredient(name: 'Bubur', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Buncis', units: ['gram', 'ikat']),
  Ingredient(name: 'Cabe', units: ['gram', 'buah']),
  Ingredient(name: 'Cabai Hijau', units: ['gram', 'buah']),
  Ingredient(name: 'Cabai Merah', units: ['gram', 'buah']),
  Ingredient(name: 'Cabai Rawit', units: ['gram', 'buah']),
  Ingredient(name: 'Cengkeh', units: ['gram', 'bungkus']),
  Ingredient(name: 'Coklat Bubuk', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Daun Bayam', units: ['gram', 'ikat']),
  Ingredient(name: 'Daun Jeruk', units: ['gram', 'lembar']),
  Ingredient(name: 'Daun Salam', units: ['gram', 'lembar']),
  Ingredient(name: 'Daging Ayam', units: ['gram', 'potong']),
  Ingredient(name: 'Daging Babi', units: ['gram', 'potong']),
  Ingredient(name: 'Daging Bebek', units: ['gram', 'potong']),
  Ingredient(name: 'Daging Ikan', units: ['gram', 'potong']),
  Ingredient(name: 'Daging Kambing', units: ['gram', 'potong']),
  Ingredient(name: 'Daging Sapi', units: ['gram', 'potong']),
  Ingredient(name: 'Edamame', units: ['gram', 'porsi']),
  Ingredient(name: 'Ebi', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Emping', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Feta Cheese', units: ['gram', 'potong']),
  Ingredient(name: 'Garam', units: ['gram', 'sendok teh']),
  Ingredient(name: 'Gula', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Gula Aren', units: ['gram', 'potong']),
  Ingredient(name: 'Gula Pasir', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Hati Ayam', units: ['gram', 'potong']),
  Ingredient(name: 'Horenzo', units: ['gram', 'ikat']),
  Ingredient(name: 'Ikan Asin', units: ['gram', 'potong']),
  Ingredient(name: 'Jahe', units: ['gram', 'potong']),
  Ingredient(name: 'Jagung Manis', units: ['gram', 'buah']),
  Ingredient(name: 'Jambu Biji', units: ['gram', 'buah']),
  Ingredient(name: 'Keju Parut', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Kecap Inggris', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Labu', units: ['gram', 'potong']),
  Ingredient(name: 'Lada Putih', units: ['gram', 'sendok teh']),
  Ingredient(name: 'Lengkuas', units: ['gram', 'potong']),
  Ingredient(name: 'Lobak', units: ['gram', 'potong']),
  Ingredient(name: 'Madu', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Mangga', units: ['gram', 'potong']),
  Ingredient(name: 'Mayones', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Mentega', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Miso', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Minyak Goreng', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Minyak Wijen', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Nangka', units: ['gram', 'potong']),
  Ingredient(name: 'Nasi', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Nasi Kuning', units: ['gram', 'porsi']),
  Ingredient(name: 'Oat', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Oatmeal', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Olive Oil', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Oregano', units: ['gram', 'sendok teh']),
  Ingredient(name: 'Pandan', units: ['gram', 'lembar']),
  Ingredient(name: 'Paprika', units: ['gram', 'buah']),
  Ingredient(name: 'Perkedel', units: ['gram', 'buah']),
  Ingredient(name: 'Pisang', units: ['gram', 'buah']),
  Ingredient(name: 'Quail Eggs', units: ['buah', 'biji']),
  Ingredient(name: 'Quinoa', units: ['gram', 'porsi']),
  Ingredient(name: 'Ragi', units: ['gram', 'sendok teh']),
  Ingredient(name: 'Rumput Laut', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Sagu', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Saus Tiram', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Sarden', units: ['gram', 'kaleng']),
  Ingredient(name: 'Sereh', units: ['gram', 'batang']),
  Ingredient(name: 'Soy Sauce', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Susua Bubuk', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Telur', units: ['buah', 'biji']),
  Ingredient(name: 'Tahu', units: ['gram', 'potong']),
  Ingredient(name: 'Tepung Terigu', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Terasi', units: ['gram', 'potong']),
  Ingredient(name: 'Tomat', units: ['gram', 'buah']),
  Ingredient(name: 'Tauge', units: ['gram', 'porsi']),
  Ingredient(name: 'Ubi', units: ['gram', 'buah']),
  Ingredient(name: 'Udang', units: ['gram', 'ekor']),
  Ingredient(name: 'Vermicelli', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Vinegar', units: ['ml', 'sendok makan']),
  Ingredient(name: 'Wheat Flour', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Wijen', units: ['gram', 'sendok makan']),
  Ingredient(name: 'Xanthan Gum', units: ['gram', 'sendok teh']),
  Ingredient(name: 'Yogurt', units: ['ml', 'gelas']),
  Ingredient(name: 'Zaitun', units: ['gram', 'buah']),
];
